### ISSUE TITLE
Rei crash

### ISSUE THREAD

**Issue by tombula77** [AMPZNetwork/All-The-Fabric-3#2]
Roughly enough items crash my game after typing "iro" in search box. I try upgrada and downgarde, nothing works.

Crash Report

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/10/22, 6:08 PM
Description: Adding entry

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2499.method_10601()" because "nbt" is null
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryPalette.deserializeNBT(SimpleStateEntryPalette.java:59)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:306)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:30)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.lambda$deserializeNBT$0(SingleBlockMultiStateItemStack.java:776)
	at mod.chiselsandbits.utils.GZIPDataCompressionUtils.decompress(GZIPDataCompressionUtils.java:60)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:775)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:769)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.lambda$deserializeNBT$1(LegacyVersionedStorageEngine.java:39)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.deserializeNBT(LegacyVersionedStorageEngine.java:39)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:51)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:11)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.deserializeNBT(SingleBlockMultiStateItemStack.java:389)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.<init>(SingleBlockMultiStateItemStack.java:73)
	at mod.chiselsandbits.item.ChiseledBlockItem.createItemStack(ChiseledBlockItem.java:53)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$6(DataAwareChiseledBlockBakedModel.java:72)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:71)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:234)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:227)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:77)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:340)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:738)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:637)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.class_757.handler$zei000$renderScreenPost(class_757.java:11059)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryPalette.deserializeNBT(SimpleStateEntryPalette.java:59)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:306)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:30)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.lambda$deserializeNBT$0(SingleBlockMultiStateItemStack.java:776)
	at mod.chiselsandbits.utils.GZIPDataCompressionUtils.decompress(GZIPDataCompressionUtils.java:60)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:775)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:769)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.lambda$deserializeNBT$1(LegacyVersionedStorageEngine.java:39)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.deserializeNBT(LegacyVersionedStorageEngine.java:39)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:51)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:11)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.deserializeNBT(SingleBlockMultiStateItemStack.java:389)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.<init>(SingleBlockMultiStateItemStack.java:73)
	at mod.chiselsandbits.item.ChiseledBlockItem.createItemStack(ChiseledBlockItem.java:53)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$6(DataAwareChiseledBlockBakedModel.java:72)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:71)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)

-- Screen details --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:90)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:340)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:738)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:637)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.class_757.handler$zei000$renderScreenPost(class_757.java:11059)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by LabsZero** [comment]
Thank you for your report i shell look into a fix as soon as i can
